#For now, we are going to try and replicate just the 3.6 python tasks, 
#and just in order. Will go back and add matrixing later.
jobs:
- job: PythonBuildOnLinux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  #Specify the Python Version to use.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: 'Set Python version to use to $(python.version)'

  # Install the package dependencies
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'sudo apt-get install libssl-dev libffi-dev python-dev'
    displayName: 'Install libssl-dev, libffi-dev, and python-dev dependencies'

  #Upgrade pip
  - script: 'python -m pip install --upgrade pip setuptools'
    displayName: 'Upgrade pip setup tools'

  #Install tox
  - script: 'pip install tox'
    displayName: 'Install tox'

  #Install wheel
  - script: 'pip install wheel'
    displayName: 'pip install wheel'

  #Precheck Stages - 
  - script: './scripts/ci/precheck_pep8.sh'
    displayName: "precheck pep8"
    workingDirectory: './'