#You can have multiple jobs in a build.
jobs:
- job: PythonBuildOnLinux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'

  steps:
  
  # Install the dependencies
  - task: Bash@3
    inputs:
      displayName: 'Install libssl-dev dependency'
      targetType: 'inline'
      script: 'sudo apt-get install libssl-dev'
  - task: Bash@3
    inputs:
      displayName: 'Install libffi-dev dependency'
      targetType: 'inline'
      script: 'sudo apt-get install libffi-dev'
  - task: Bash@3
    inputs:
      displayName: 'Install python-dev dependency'
      targetType: 'inline'
      script: 'sudo apt-get install python-dev'

  #Install tools
  - script: 'python -m pip install --upgrade pip setuptools'
    displayName: 'Install tools'      

  #Upgrading pip
  - script: 'pip install --upgrade pip'
    displayName: 'upgrading pip'