#You can have multiple jobs in a build.
jobs:
- job: PythonBuildOnLinux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'

  steps:
  # Install the dependencies
  - bash: |
    'apt-get install libssl-dev'

  - task: PublishArtifacts
    displayname: 'I don't do anything yet'